
platform :ios, '9.0'
use_frameworks!
target 'NearX_iOS_Tests' do
  pod 'NearX_iOS', :path => '../'
  pod 'ObjectMapper', '3.3'
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'SwiftyJSON' , '~> 4.2.0'
end
